parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       smtp.sendgrid.net
    mailer_user:       sas05
    mailer_password:   05sas3014

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
