nmpolo_rest:
    resource: "@FaithleadRestBundle/Controller/"
    type:     annotation
    prefix:   /

faithlead_rest:
    resource: "@FaithleadRestBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
