<?php

/**
 * @author Eftakahirul Islam  <eftakhairul@gmail.com>
 * Copyright @ Faithlead
 */
namespace Faithlead\RestBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * EmailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateRepository extends DocumentRepository
{
    /**
     * Return count of email templates by user id
     *
     * @param $userId
     * @return bool|int
     */
    public function countByUserId($userId)
    {
        if (empty($id)) return false;

//        FIXME: Have to write function query builder
        $total = $this->findBy(array('user' => $userId));
        return empty($total)? 0 : count($total);
    }
}