<?php

/**
 * @author Eftakahirul Islam  <eftakhairul@gmail.com>
 * Copyright @ Faithlead
 */
namespace Faithlead\RestBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * EmailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateRepository extends DocumentRepository
{
    /**
     * Return count of email templates by user id
     *
     * @param $userId
     * @return bool|int
     */
    public function countByUserId($userId)
    {
        if (empty($userId)) return 0;

        $total = $this->createQueryBuilder('e')
                      ->field('user')->equals($userId)
                      ->getQuery()
                      ->execute()
                      ->count();

        return empty($total)? 0 : $total;
    }
}